### PR TITLE
221-wrong-nor-error: fix nor bug and test cases

### LINKED ISSUE #221: Wrong nor error
The nor key must be a relative path. There is currently a bug when checking if this key is a relative path or not, it returns that a path is not relative when it actually is. The purpose of this ticket is to identify the problem and fix it.

AC 
- Fix the bug

### PR DESCRIPTION
**Pull request by adriansqualabs**

### CODE REVIEW

**Review by JoaquinBCh — APPROVED** [review]

File: packages/cmcd-validator-library/src/keyValueValidator/validatorFunctions.js [hunk 1]
```diff
@@ -21,7 +21,7 @@ export const isEncoded = (errors, key, value, requestID) => {
 };
 
 export const isRelativePath = (errors, key, value, requestID) => {
-  if (!(/^(\.\/|\.\.\/)/.test(decodeURIComponent(value)))) {
+  if (!(/^(\.\/|\.\.\/{0,1})/.test(decodeURIComponent(value)))) {
```
Comment (JoaquinBCh) [inline packages/cmcd-validator-library/src/keyValueValidator/validatorFunctions.js]: We descuss with the team and we agreed that the url must not match this regex ```^(http\:\/\/|https\:\/\/)```

Comment (JoaquinBCh) [inline packages/cmcd-validator-library/src/keyValueValidator/validatorFunctions.js]:
```suggestion
  if ((/^(http\:\/\/|https\:\/\/)/.test(decodeURIComponent(value)))) {
```

**Review by coatesjuan — APPROVED** [review]

**Review by JoaquinBCh — APPROVED** [review]
